import { Timestamp } from 'firebase/firestore';

// 制作費の内訳
export interface ProductionFeeBreakdown {
  initialPayment?: number; // 初期費用
  initialPaymentDueDate?: Timestamp; // 初期費用請求日
  initialPaymentPaid?: boolean; // 初期費用支払済み

  intermediatePayment?: number; // 中間費用
  intermediatePaymentDueDate?: Timestamp; // 中間費用請求日
  intermediatePaymentPaid?: boolean; // 中間費用支払済み

  finalPayment?: number; // 最終金
  finalPaymentDueDate?: Timestamp; // 最終金請求日
  finalPaymentPaid?: boolean; // 最終金支払済み
}

// クライアント情報
export interface Client {
  id: string;
  clientName: string;
  email?: string;
  phone?: string;
  address?: string;
  userId?: string; // Firebase認証のUID（クライアントがログインする場合）
  stripeCustomerId?: string; // Stripe Customer ID
  subscriptionId?: string; // 現在のサブスクリプションID
  subscriptionStatus?: 'active' | 'past_due' | 'canceled' | 'incomplete' | 'trialing';
  currentPlanId?: string; // 現在のプランID

  // 契約情報
  contractStartDate?: Timestamp; // 契約開始日
  contractEndDate?: Timestamp; // 契約終了日
  productionFee?: number; // 制作費（合計）※後方互換性のため残す
  productionFeePaid?: boolean; // 制作費支払済みフラグ※後方互換性のため残す
  productionFeeBreakdown?: ProductionFeeBreakdown; // 制作費の内訳

  // 管理費スケジュール
  managementFeeSchedule?: ManagementFeeSchedule[];

  // 請求設定
  billingFrequency?: 'monthly' | 'yearly'; // 請求頻度（月額 or 年額）
  lastPaidPeriod?: string; // 最後に支払った期間（YYYY-MM形式）
  accumulatedDifference?: number; // 累積過不足金（過払いならプラス、不足ならマイナス）

  // 支払い方法
  paymentMethod?: 'credit_card' | 'bank_transfer' | 'bank_debit'; // クレジットカード or 銀行振込 or 口座引き落とし
  stripePaymentMethodId?: string; // Stripe Payment Method ID
  cardLast4?: string; // カード下4桁
  cardBrand?: string; // カードブランド（visa, mastercard, etc.）

  // マイページアクセス用
  mypageToken?: string; // マイページアクセス用のユニークトークン（後方互換性のため残す）

  // 認証情報
  authUid?: string; // Firebase Authentication UID
  emailVerified?: boolean; // メールアドレス確認済みフラグ
  hasInitialPassword?: boolean; // 初期パスワードを使用中かどうか

  createdAt: Timestamp;
  updatedAt: Timestamp;
  isActive: boolean;
}

// 管理費スケジュール
export interface ManagementFeeSchedule {
  fromMonth?: number; // 何ヶ月目から（1から開始）※後方互換性のため残す
  toMonth?: number; // 何ヶ月目まで（未指定の場合は無期限）※後方互換性のため残す
  fromDate?: Timestamp; // 開始日（日付ベース）
  toDate?: Timestamp; // 終了日（未指定の場合は無期限）
  monthlyFee: number; // 月額管理費
  description?: string; // 説明（例：「月額管理費用1」「月額管理費用2」）
}

// 請求書アイテム
export interface InvoiceItem {
  description: string;
  quantity: number;
  unitPrice: number;
  amount: number;
}

// 請求書ステータス
export type InvoiceStatus = 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';

// 請求書
export interface Invoice {
  id: string;
  clientId: string;
  clientName: string; // 非正規化: 表示用
  invoiceNumber: string;
  items: InvoiceItem[];
  subtotal: number;
  taxRate: number; // 10% = 0.1 (免税の場合は0)
  taxAmount: number;
  totalAmount: number;
  issueDate: Timestamp;
  dueDate: Timestamp;
  status: InvoiceStatus;
  notes?: string;

  // 請求期間情報
  quantity?: number; // 請求月数（月額の場合は未払い月数、年額の場合は11）
  billingPeriodStart?: Timestamp; // 請求期間開始日
  billingPeriodEnd?: Timestamp; // 請求期間終了日

  // 自動生成情報
  isAutoGenerated?: boolean; // 自動生成された請求書かどうか
  billingMonth?: string; // 請求対象月（例：'2025-11'）

  // Stripe関連
  stripePaymentIntentId?: string;
  stripeCheckoutSessionId?: string;

  // 支払い情報
  paidAt?: Timestamp;
  paidAmount?: number; // 実際に支払われた金額
  paymentDifference?: number; // 過不足金（totalAmount - paidAmount）
  paymentMethod?: 'card' | 'bank_transfer' | 'other';
  manuallyMarkedAsPaid?: boolean; // 手動で支払済みにされたか
  markedAsPaidBy?: string; // 支払済みにした管理者のUID

  // PDF情報
  pdfUrl?: string; // Google DriveのPDF URL (請求書)
  pdfGeneratedAt?: string; // PDF生成日時
  receiptUrl?: string; // Google DriveのPDF URL (領収書)
  receiptGeneratedAt?: string; // 領収書PDF生成日時
  receiptDownloadCount?: number; // 領収書ダウンロード回数
  receiptFirstDownloadedAt?: Timestamp; // 領収書初回ダウンロード日時

  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// 振込先情報（Firestore設定コレクション）
export interface BankTransferInfo {
  bankName: string; // 銀行名
  branchName: string; // 支店名
  accountType: string; // 口座種別
  accountNumber: string; // 口座番号
  accountHolder: string; // 口座名義
}

// 請求書作成リクエスト
export interface CreateInvoiceRequest {
  clientId: string;
  items: Omit<InvoiceItem, 'amount'>[];
  dueDate: Date;
  notes?: string;
}

// 請求書更新リクエスト
export interface UpdateInvoiceRequest {
  items?: Omit<InvoiceItem, 'amount'>[];
  dueDate?: Date;
  status?: InvoiceStatus;
  notes?: string;
}

// クライアント作成リクエスト
export interface CreateClientRequest {
  clientName: string;
  email: string;
  phone?: string;
  address?: string;
  userId?: string;
}

// クライアント更新リクエスト
export interface UpdateClientRequest {
  clientName?: string;
  email?: string;
  phone?: string;
  address?: string;
  isActive?: boolean;
}

// Stripe Checkout Session作成リクエスト
export interface CreateCheckoutSessionRequest {
  invoiceId: string;
}

// Stripe Checkout Session作成レスポンス
export interface CreateCheckoutSessionResponse {
  sessionId: string;
  url: string;
}

// サブスクリプションプラン
export interface SubscriptionPlan {
  id: string;
  name: string;
  description?: string;
  amount: number;
  currency: string;
  interval: 'month' | 'year';
  stripePriceId?: string;
  stripeProductId?: string;
  isActive: boolean;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// サブスクリプション
export interface Subscription {
  id: string;
  clientId: string;
  stripeSubscriptionId: string;
  stripeCustomerId: string;
  planId: string;
  planName: string;
  amount: number;
  status: 'active' | 'past_due' | 'canceled' | 'incomplete' | 'trialing';
  currentPeriodStart: Timestamp;
  currentPeriodEnd: Timestamp;
  cancelAtPeriodEnd: boolean;
  canceledAt?: Timestamp;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// サブスクリプション作成リクエスト
export interface CreateSubscriptionRequest {
  clientId: string;
  planId: string;
}

// サブスクリプション作成レスポンス
export interface CreateSubscriptionResponse {
  subscriptionId: string;
  clientSecret?: string;
}

// ==================== 経費管理 ====================

// 経費カテゴリ
export type ExpenseCategory =
  // 共通カテゴリ
  | 'communication' // 通信費
  | 'transportation' // 交通費
  | 'supplies' // 消耗品費
  | 'utilities' // 水道光熱費
  | 'rent' // 地代家賃
  | 'outsourcing' // 外注費
  | 'advertising' // 広告宣伝費
  | 'entertainment' // 接待交際費
  | 'insurance' // 保険料
  | 'depreciation' // 減価償却費
  | 'taxes' // 租税公課
  | 'professional_fees' // 専門家報酬
  | 'software' // ソフトウェア費
  | 'education' // 研修費
  // 法人専用カテゴリ
  | 'officer_compensation' // 役員報酬
  | 'employee_salary' // 従業員給与
  | 'welfare_expenses' // 福利厚生費
  | 'meeting_expenses' // 会議費
  | 'statutory_welfare' // 法定福利費
  | 'other'; // その他

// 経費カテゴリのラベル
export const EXPENSE_CATEGORY_LABELS: Record<ExpenseCategory, string> = {
  communication: '通信費',
  transportation: '交通費',
  supplies: '消耗品費',
  utilities: '水道光熱費',
  rent: '地代家賃',
  outsourcing: '外注費',
  advertising: '広告宣伝費',
  entertainment: '接待交際費',
  insurance: '保険料',
  depreciation: '減価償却費',
  taxes: '租税公課',
  professional_fees: '専門家報酬',
  software: 'ソフトウェア費',
  education: '研修費',
  officer_compensation: '役員報酬',
  employee_salary: '従業員給与',
  welfare_expenses: '福利厚生費',
  meeting_expenses: '会議費',
  statutory_welfare: '法定福利費',
  other: 'その他',
};

// 法人専用カテゴリのリスト
export const CORPORATION_ONLY_CATEGORIES: ExpenseCategory[] = [
  'officer_compensation',
  'employee_salary',
  'welfare_expenses',
  'meeting_expenses',
  'statutory_welfare',
];

// 経費
export interface Expense {
  id: string;
  date: Timestamp; // 支払日
  category: ExpenseCategory;
  amount: number; // 金額
  description: string; // 摘要
  vendor?: string; // 支払先
  receiptUrl?: string; // 領収書画像のURL
  taxDeductible: boolean; // 経費として計上可能か
  homeUseRatio?: number; // 家事按分率（0-100）※個人事業主用
  deductibleAmount?: number; // 実際の経費計上額（按分後）
  paymentMethod?: 'cash' | 'card' | 'bank_transfer' | 'other';
  memo?: string; // メモ
  tags?: string[]; // タグ（プロジェクト名など）
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// ==================== 資産管理 ====================

// 固定資産
export interface FixedAsset {
  id: string;
  name: string; // 資産名
  category: 'building' | 'equipment' | 'vehicle' | 'software' | 'other';
  acquisitionDate: Timestamp; // 取得日
  acquisitionCost: number; // 取得価額
  usefulLife: number; // 耐用年数（年）
  depreciationMethod: 'straight_line' | 'declining_balance'; // 定額法 or 定率法
  residualValue?: number; // 残存価額
  currentBookValue?: number; // 現在の帳簿価額
  accumulatedDepreciation?: number; // 減価償却累計額
  memo?: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// ==================== 財務諸表 ====================

// 損益計算書（P/L）
export interface ProfitAndLoss {
  id: string;
  fiscalYear: string; // 会計年度（例：'2024'）
  fiscalPeriod?: string; // 期間（例：'2024-01'）月次の場合

  // 売上
  revenue: number; // 売上高

  // 売上原価
  costOfGoodsSold?: number; // 売上原価
  grossProfit?: number; // 売上総利益

  // 販売費及び一般管理費
  expenses: {
    communication: number;
    transportation: number;
    supplies: number;
    utilities: number;
    rent: number;
    outsourcing: number;
    advertising: number;
    entertainment: number;
    insurance: number;
    depreciation: number;
    taxes: number;
    professionalFees: number;
    software: number;
    education: number;
    other: number;
  };
  totalExpenses: number; // 販管費合計

  operatingProfit: number; // 営業利益

  // 営業外収益・費用
  nonOperatingIncome?: number; // 営業外収益
  nonOperatingExpenses?: number; // 営業外費用

  ordinaryProfit: number; // 経常利益

  // 特別損益
  extraordinaryIncome?: number; // 特別利益
  extraordinaryLoss?: number; // 特別損失

  profitBeforeTax: number; // 税引前当期純利益
  incomeTax?: number; // 法人税等
  netProfit: number; // 当期純利益

  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// 貸借対照表（B/S）
export interface BalanceSheet {
  id: string;
  fiscalYear: string; // 会計年度
  asOfDate: Timestamp; // 基準日

  // 資産の部
  assets: {
    // 流動資産
    currentAssets: {
      cash: number; // 現金
      bankDeposits: number; // 預金
      accountsReceivable: number; // 売掛金
      inventory?: number; // 棚卸資産
      other: number; // その他
      total: number; // 流動資産合計
    };

    // 固定資産
    fixedAssets: {
      tangibleAssets: number; // 有形固定資産
      intangibleAssets: number; // 無形固定資産
      investments?: number; // 投資その他の資産
      total: number; // 固定資産合計
    };

    total: number; // 資産合計
  };

  // 負債の部
  liabilities: {
    // 流動負債
    currentLiabilities: {
      accountsPayable: number; // 買掛金
      shortTermLoans?: number; // 短期借入金
      accrued?: number; // 未払金
      other: number; // その他
      total: number; // 流動負債合計
    };

    // 固定負債
    longTermLiabilities: {
      longTermLoans?: number; // 長期借入金
      other: number; // その他
      total: number; // 固定負債合計
    };

    total: number; // 負債合計
  };

  // 純資産の部
  netAssets: {
    capital: number; // 資本金
    retainedEarnings: number; // 利益剰余金
    total: number; // 純資産合計
  };

  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// ==================== キャッシュフロー ====================

// キャッシュフロー計算書
export interface CashFlowStatement {
  id: string;
  fiscalYear: string;
  fiscalPeriod?: string;

  // 営業活動によるキャッシュフロー
  operatingActivities: {
    netProfit: number;
    depreciation: number;
    increaseInReceivables: number;
    increaseInPayables: number;
    other: number;
    total: number;
  };

  // 投資活動によるキャッシュフロー
  investingActivities: {
    purchaseOfFixedAssets: number;
    other: number;
    total: number;
  };

  // 財務活動によるキャッシュフロー
  financingActivities: {
    proceedsFromLoans: number;
    repaymentOfLoans: number;
    other: number;
    total: number;
  };

  netCashIncrease: number; // 現金及び現金同等物の増減額
  cashAtBeginning: number; // 期首現金残高
  cashAtEnd: number; // 期末現金残高

  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// ==================== 事業設定 ====================

// 事業形態
export type BusinessType = 'sole_proprietorship' | 'corporation';

// 確定申告方法（個人事業主用）
export type TaxFilingMethod = 'blue' | 'white'; // 青色申告 or 白色申告

// 青色申告特別控除額
export type BlueReturnDeduction = 65 | 55 | 10; // 65万円 or 55万円 or 10万円

// 事業設定
export interface BusinessSettings {
  id: string;
  businessType: BusinessType; // 事業形態

  // 個人事業主用
  taxFilingMethod?: TaxFilingMethod; // 申告方法
  blueReturnDeduction?: BlueReturnDeduction; // 青色申告特別控除額

  // 法人用
  fiscalYearEnd?: string; // 決算日（'03-31', '12-31'など MM-DD形式）
  incorporationDate?: Timestamp; // 法人化日
  capitalStock?: number; // 資本金
  representativeName?: string; // 代表者名

  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// ==================== 予算管理 ====================

// 予算
export interface Budget {
  id: string;
  fiscalYear: string;
  fiscalPeriod?: string; // 月次予算の場合

  // 収入予算
  revenueTarget: number;

  // 支出予算（カテゴリ別）
  expenseBudgets: {
    [key in ExpenseCategory]?: number;
  };
  totalExpenseBudget: number;

  // 目標利益
  targetProfit: number;

  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// ==================== レポート ====================

// 月次レポート
export interface MonthlyReport {
  id: string;
  year: number;
  month: number; // 1-12

  // 売上
  revenue: number;
  revenueGrowth?: number; // 前月比（%）
  revenueYoY?: number; // 前年同月比（%）

  // 経費
  expenses: number;
  expensesGrowth?: number;
  expensesYoY?: number;

  // 利益
  profit: number;
  profitMargin: number; // 利益率（%）

  // 予算との比較
  budgetVariance?: {
    revenue: number; // 予算差異
    expenses: number;
    profit: number;
  };

  // キャッシュフロー
  cashFlow: {
    beginning: number; // 月初残高
    inflow: number; // 入金
    outflow: number; // 出金
    ending: number; // 月末残高
  };

  // 主要指標
  kpis: {
    numberOfInvoices: number; // 請求書数
    averageInvoiceAmount: number; // 平均請求額
    collectionRate: number; // 回収率（%）
    numberOfClients: number; // 顧客数
  };

  createdAt: Timestamp;
}

// ==================== 税務計算 ====================

// 源泉徴収
export interface WithholdingTax {
  id: string;
  invoiceId: string;
  clientId: string;
  clientName: string;
  amount: number; // 源泉徴収額
  paymentAmount: number; // 支払額（源泉徴収前）
  date: Timestamp;
  fiscalYear: string;
  createdAt: Timestamp;
}

// 年度別源泉徴収集計
export interface AnnualWithholdingTaxSummary {
  fiscalYear: string;
  totalWithheld: number; // 年間源泉徴収額合計
  items: WithholdingTax[];
  createdAt: Timestamp;
}

// 確定申告データ
export interface TaxReturnData {
  id: string;
  fiscalYear: string;

  // 収入
  revenue: number; // 売上

  // 経費
  expenses: {
    [key in ExpenseCategory]: number;
  };
  totalExpenses: number;

  // 所得
  businessIncome: number; // 事業所得（売上 - 経費）
  blueReturnDeduction?: number; // 青色申告特別控除
  taxableIncome: number; // 課税所得

  // 源泉徴収
  withholdingTax: number; // 源泉徴収税額

  // 納税額
  estimatedIncomeTax?: number; // 概算所得税
  estimatedResidentTax?: number; // 概算住民税
  estimatedBusinessTax?: number; // 概算事業税

  createdAt: Timestamp;
  updatedAt: Timestamp;
}
